version: 2

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    disable:
      - printf

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
