run:
  timeout: 5m
  go: "1.21"

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  govet:
    disable:
      - printf

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
