run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
